services:
  db:
    image: postgres:17
    container_name: bank-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_app

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend

    container_name: bank-backend

    ports:
      - "8000:8000"

    env_file:
      - .env.docker

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/bank_app
      REDIS_URL: redis://redis:6379


  frontend:
    build: ./frontend

    container_name: bank-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

  redis:
    image: redis:7

    container_name: bank-redis
    
    ports:
      - "6379:6379"

  celery_worker:
    build: backend

    command: celery -A tasks.celery_app worker --loglevel=info
    
    env_file:
      - .env.docker
    
    depends_on:
      - backend
      - redis

    

volumes:
  postgres_data: