"""add transfer table

Revision ID: 4e8e514ff17a
Revises: e9713222ea96
Create Date: 2026-08-31 23:37:05.883395

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e8e514ff17a"
down_revision: Union[str, Sequence[str], None] = "e9713222ea96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transfers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("from_account_id", sa.UUID(), nullable=False),
        sa.Column("to_account_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transfers_idempotency_key"),
        "transfers",
        ["idempotency_key"],
        unique=True,
    )
    op.add_column("transactions", sa.Column("transfer_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("ix_transactions_idempotency_key"), table_name="transactions")
    op.create_foreign_key(None, "transactions", "transfers", ["transfer_id"], ["id"])
    op.drop_column("transactions", "idempotency_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "idempotency_key",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.create_index(
        op.f("ix_transactions_idempotency_key"),
        "transactions",
        ["idempotency_key"],
        unique=True,
    )
    op.drop_column("transactions", "transfer_id")
    op.drop_index(op.f("ix_transfers_idempotency_key"), table_name="transfers")
    op.drop_table("transfers")
    # ### end Alembic commands ###
