"""temporary idempotency_key in transactions table

Revision ID: c00d8c18bf5b
Revises: 4e8e514ff17a
Create Date: 2026-09-01 00:06:21.314328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c00d8c18bf5b"
down_revision: Union[str, Sequence[str], None] = "4e8e514ff17a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_transactions_idempotency_key"),
        "transactions",
        ["idempotency_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_idempotency_key"), table_name="transactions")
    op.drop_column("transactions", "idempotency_key")
    # ### end Alembic commands ###
