"""balance_before/after, status & idempotency_key fields added to Transaction

Revision ID: e9713222ea96
Revises: 8a0c5b8c15c2
Create Date: 2026-08-16 22:41:34.483688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9713222ea96"
down_revision: Union[str, Sequence[str], None] = "8a0c5b8c15c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("balance_before", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    op.add_column(
        "transactions", sa.Column("status", sa.String(length=12), nullable=False)
    )
    op.add_column(
        "transactions",
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
    )
    op.create_index(
        op.f("ix_transactions_idempotency_key"),
        "transactions",
        ["idempotency_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_idempotency_key"), table_name="transactions")
    op.drop_column("transactions", "idempotency_key")
    op.drop_column("transactions", "status")
    op.drop_column("transactions", "balance_after")
    op.drop_column("transactions", "balance_before")
    # ### end Alembic commands ###
